In [189]:
from qiskit import *
import numpy as np
import scipy.linalg as la

In [141]:
num_qubits = 5
backend = Aer.get_backend('qasm_simulator')
shots = 8192

In [142]:
group = [[0,2,4,7,9,11,13,15,19,21,23,25,27,30,32,34,36,38,42,44,46,48,50]
          ,[1,3,5,6,8,10,12,14,16,17,18,20,22,24,26,28,29,31,33,35,37,39,40,41,43,45,47,49,51,52]]

In [204]:
coupling_map = [
    (0, 1), (2, 3), (4, 6), (12, 13), (10, 11), (5, 9), (21, 22), (23, 24), (25, 29), (35, 36), (33, 34), (28, 32), (44, 45), (46, 47), (48, 52), (7, 16), (30, 39), (18, 27), (41, 50), (7, 8), (9, 10), (11, 17), (22, 23), (20, 21), (16, 19), (30, 31), (32, 33), (34, 40), (45, 46), (43, 44), (39, 42), (14, 15), (6, 13), (25, 26), (37, 38), (29, 36), (48, 49), (1, 2), (0, 5), (8, 9), (19, 20), (21, 28), (31, 32), (42, 43), (44, 51), (11, 12), (13, 14), (15, 18), (26, 27), (24, 25), (17, 23), (34, 35), (36, 37), (38, 41), (49, 50), (47, 48), (40, 46), (3, 4)
]

In [149]:
circuit = {string:QuantumCircuit(num_qubits) for string in ['00', '01', '10', '11']}
for string in circuit:
    for g in range(2):
        if string[g]=='1':
            for j in group[g]:
                if j < num_qubits:
                    circuit[string].x(j)
                    
meas = QuantumCircuit(num_qubits,num_qubits)
for j in range(num_qubits):
    meas.measure(j,j)

In [150]:
circuit_list = [circuit[string]+meas for string in ['00', '01', '10', '11']]
results = execute(circuit_list, backend, shots=shots).result()
miti_counts = {string:results.get_counts(int(string,2)) for string in circuit}

In [179]:
miti_counts = {'00': {'00000': 8000, '11111': 192},
 '01': {'01010': 8000, '10101': 192},
 '10': {'10101': 8000, '01010': 192},
 '11': {'11111': 7000,'00000': 1192}}

In [200]:
M = {}
Minv = {}
for (q0,q1) in coupling_map:
    M[q0,q1] = [[0 for _ in range(4)] for _ in range(4)]
    if q0<num_qubits and q1<num_qubits:
        for string in ['00', '01', '10', '11']:
            for output in miti_counts[string]:
                measured_string = output[-q0-1] + output[-q1-1]
                if q0 in group[1]:
                    measured_string = measured_string[::-1]
                M[q0,q1][int(measured_string,2)][int(string,2)] += miti_counts[string][output]/shots
                Minv[q0,q1] = la.pinv( M[q0,q1] ) 

In [ ]:
def counts2prob(counts)

In [201]:
np.dot(M[q0,q1],[1,0,0,0])

array([0.9765625, 0.       , 0.       , 0.0234375])

In [202]:
np.dot(M[q0,q1],[0,0,0,1])

array([0.14550781, 0.        , 0.        , 0.85449219])

In [203]:
np.dot(Minv[q0,q1],[0.9765625, 0.       , 0.       , 0.0234375])

array([1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 1.73472348e-17])

In [219]:
np.random.normal(scale=0.5/np.sqrt(shots))

0.0007633088733403042

In [220]:
import time

In [228]:
time.time()

1581350767.304697

In [229]:
qc = QuantumCircuit(3)

In [231]:
qc.ch()

TypeError: ch() missing 2 required positional arguments: 'ctl' and 'tgt'

In [232]:
(1,(1,2))

(1, (1, 2))